/**
 * Built-in API contract templates for the New Scan workflow.
 *
 * Each generator returns a VALID OpenAPI 3.0.3 JSON document (as a string)
 * that passes Shulker's spec validator and inventory import pipeline with
 * no file upload. Pure TypeScript — no React — so it is unit-testable from
 * scripts/e2e.mjs.
 */

export type TemplateId = 'gemini' | 'openai' | 'github' | 'stripe' | 'custom';

export interface TemplateMeta {
  id: TemplateId;
  label: string;
  description: string;
  target: string;
  authMode: 'api-key' | 'bearer';
  headerName?: string; // api-key mode only
  keyUrl: string; // where the user obtains a key
}

export const TEMPLATES: Array<TemplateMeta> = [
  {
    id: 'gemini',
    label: 'Gemini API',
    description: 'Google Generative Language API — models, generateContent, streaming.',
    target: 'https://generativelanguage.googleapis.com',
    authMode: 'api-key',
    headerName: 'x-goog-api-key',
    keyUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'openai',
    label: 'OpenAI API',
    description: 'Chat completions, embeddings and model listing.',
    target: 'https://api.openai.com',
    authMode: 'bearer',
    keyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'github',
    label: 'GitHub API',
    description: 'Repos, issues, user and search endpoints.',
    target: 'https://api.github.com',
    authMode: 'bearer',
    keyUrl: 'https://github.com/settings/tokens',
  },
  {
    id: 'stripe',
    label: 'Stripe API',
    description: 'Charges, customers and balance endpoints.',
    target: 'https://api.stripe.com',
    authMode: 'bearer',
    keyUrl: 'https://dashboard.stripe.com/apikeys',
  },
];

const jsonResp = (description: string, schema?: Record<string, unknown>) => ({
  description,
  ...(schema ? { content: { 'application/json': { schema } } } : {}),
});

const errResp = jsonResp('Error envelope', {
  type: 'object',
  properties: { error: { type: 'object', properties: { message: { type: 'string' } } } },
});

function spec(opts: {
  title: string;
  description: string;
  securitySchemes: Record<string, unknown>;
  security: Array<Record<string, string[]>>;
  paths: Record<string, unknown>;
}): string {
  return JSON.stringify(
    {
      openapi: '3.0.3',
      info: {
        title: opts.title,
        description: opts.description,
        version: '1.0.0',
        'x-shulker-template': true,
      },
      servers: [],
      components: { securitySchemes: opts.securitySchemes },
      security: opts.security,
      paths: opts.paths,
    },
    null,
    2,
  );
}

/* ------------------------------------------------------------------ */
/* Gemini — API key in x-goog-api-key header                           */
/* ------------------------------------------------------------------ */

export function geminiSpec(): string {
  const model = {
    type: 'object',
    properties: {
      name: { type: 'string' },
      displayName: { type: 'string' },
      supportedGenerationMethods: { type: 'array', items: { type: 'string' } },
    },
  };
  return spec({
    title: 'Google Gemini API (Generative Language)',
    description: 'Generated by Shulker — list models and generate content with an API key.',
    securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'x-goog-api-key' } },
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/v1beta/models': {
        get: {
          operationId: 'listModels',
          summary: 'Lists available Gemini models',
          tags: ['Models'],
          parameters: [
            { name: 'pageSize', in: 'query', schema: { type: 'integer' } },
            { name: 'pageToken', in: 'query', schema: { type: 'string' } },
          ],
          responses: {
            '200': jsonResp('Model list', {
              type: 'object',
              properties: { models: { type: 'array', items: model } },
            }),
            '403': errResp,
          },
        },
      },
      '/v1beta/models/{model}': {
        get: {
          operationId: 'getModel',
          summary: 'Fetch a single model',
          tags: ['Models'],
          parameters: [{ name: 'model', in: 'path', required: true, schema: { type: 'string' } }],
          responses: { '200': jsonResp('Model', model), '404': errResp },
        },
      },
      '/v1beta/models/{model}:generateContent': {
        post: {
          operationId: 'generateContent',
          summary: 'Generate content from a prompt',
          tags: ['Generation'],
          parameters: [{ name: 'model', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['contents'],
                  properties: {
                    contents: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          role: { type: 'string' },
                          parts: { type: 'array', items: { type: 'object', properties: { text: { type: 'string' } } } },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
          responses: {
            '200': jsonResp('Generation result', {
              type: 'object',
              properties: {
                candidates: { type: 'array', items: { type: 'object', properties: { content: { type: 'object' } } } },
              },
            }),
            '400': errResp,
            '429': errResp,
          },
        },
      },
    },
  });
}

/* ------------------------------------------------------------------ */
/* OpenAI — Bearer token                                               */
/* ------------------------------------------------------------------ */

export function openaiSpec(): string {
  const bearer = { BearerAuth: { type: 'http', scheme: 'bearer' } };
  return spec({
    title: 'OpenAI API',
    description: 'Generated by Shulker — chat completions, embeddings and models.',
    securitySchemes: bearer,
    security: [{ BearerAuth: [] }],
    paths: {
      '/v1/models': {
        get: {
          operationId: 'listModels',
          summary: 'List available models',
          tags: ['Models'],
          responses: {
            '200': jsonResp('Model list', {
              type: 'object',
              properties: { data: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' } } } } },
            }),
            '401': errResp,
          },
        },
      },
      '/v1/chat/completions': {
        post: {
          operationId: 'createChatCompletion',
          summary: 'Create a chat completion',
          tags: ['Chat'],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['model', 'messages'],
                  properties: {
                    model: { type: 'string' },
                    messages: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: { role: { type: 'string' }, content: { type: 'string' } },
                      },
                    },
                    temperature: { type: 'number' },
                  },
                },
              },
            },
          },
          responses: {
            '200': jsonResp('Completion', {
              type: 'object',
              properties: {
                id: { type: 'string' },
                choices: { type: 'array', items: { type: 'object', properties: { message: { type: 'object' } } } },
              },
            }),
            '401': errResp,
            '429': errResp,
          },
        },
      },
      '/v1/embeddings': {
        post: {
          operationId: 'createEmbeddings',
          summary: 'Create embeddings for text',
          tags: ['Embeddings'],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['model', 'input'],
                  properties: { model: { type: 'string' }, input: { type: 'string' } },
                },
              },
            },
          },
          responses: { '200': jsonResp('Embeddings'), '401': errResp },
        },
      },
    },
  });
}

/* ------------------------------------------------------------------ */
/* GitHub — Bearer token                                               */
/* ------------------------------------------------------------------ */

export function githubSpec(): string {
  const bearer = { BearerAuth: { type: 'http', scheme: 'bearer' } };
  const issue = {
    type: 'object',
    properties: {
      id: { type: 'integer' },
      number: { type: 'integer' },
      title: { type: 'string' },
      state: { type: 'string' },
      user: { type: 'object', properties: { login: { type: 'string' } } },
    },
  };
  return spec({
    title: 'GitHub REST API',
    description: 'Generated by Shulker — user, repos, issues and search.',
    securitySchemes: bearer,
    security: [{ BearerAuth: [] }],
    paths: {
      '/user': {
        get: {
          operationId: 'getAuthenticatedUser',
          summary: 'Get the authenticated user',
          tags: ['Users'],
          responses: {
            '200': jsonResp('User', { type: 'object', properties: { login: { type: 'string' }, id: { type: 'integer' } } }),
            '401': errResp,
          },
        },
      },
      '/repos/{owner}/{repo}': {
        get: {
          operationId: 'getRepo',
          summary: 'Get a repository',
          tags: ['Repos'],
          parameters: [
            { name: 'owner', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'repo', in: 'path', required: true, schema: { type: 'string' } },
          ],
          responses: {
            '200': jsonResp('Repository', { type: 'object', properties: { id: { type: 'integer' }, name: { type: 'string' } } }),
            '404': errResp,
          },
        },
      },
      '/repos/{owner}/{repo}/issues': {
        get: {
          operationId: 'listIssues',
          summary: 'List repository issues',
          tags: ['Issues'],
          parameters: [
            { name: 'owner', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'repo', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'state', in: 'query', schema: { type: 'string', enum: ['open', 'closed', 'all'] } },
          ],
          responses: { '200': jsonResp('Issues', { type: 'array', items: issue }), '404': errResp },
        },
        post: {
          operationId: 'createIssue',
          summary: 'Create an issue',
          tags: ['Issues'],
          parameters: [
            { name: 'owner', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'repo', in: 'path', required: true, schema: { type: 'string' } },
          ],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['title'],
                  properties: { title: { type: 'string' }, body: { type: 'string' } },
                },
              },
            },
          },
          responses: { '201': jsonResp('Issue created', issue), '422': errResp },
        },
      },
      '/search/repositories': {
        get: {
          operationId: 'searchRepositories',
          summary: 'Search repositories',
          tags: ['Search'],
          parameters: [
            { name: 'q', in: 'query', required: true, schema: { type: 'string' } },
            { name: 'per_page', in: 'query', schema: { type: 'integer' } },
          ],
          responses: { '200': jsonResp('Search results') },
        },
      },
    },
  });
}

/* ------------------------------------------------------------------ */
/* Stripe — Bearer token (secret key)                                  */
/* ------------------------------------------------------------------ */

export function stripeSpec(): string {
  const bearer = { BearerAuth: { type: 'http', scheme: 'bearer' } };
  const customer = {
    type: 'object',
    properties: {
      id: { type: 'string' },
      email: { type: 'string' },
      name: { type: 'string' },
      created: { type: 'integer' },
    },
  };
  return spec({
    title: 'Stripe API',
    description: 'Generated by Shulker — charges, customers and balance.',
    securitySchemes: bearer,
    security: [{ BearerAuth: [] }],
    paths: {
      '/v1/balance': {
        get: {
          operationId: 'getBalance',
          summary: 'Retrieve the current account balance',
          tags: ['Balance'],
          responses: {
            '200': jsonResp('Balance', {
              type: 'object',
              properties: { object: { type: 'string' }, available: { type: 'array', items: { type: 'object' } } },
            }),
            '401': errResp,
          },
        },
      },
      '/v1/charges': {
        get: {
          operationId: 'listCharges',
          summary: 'List charges',
          tags: ['Charges'],
          parameters: [
            { name: 'limit', in: 'query', schema: { type: 'integer' } },
            { name: 'customer', in: 'query', schema: { type: 'string' } },
          ],
          responses: {
            '200': jsonResp('Charge list', {
              type: 'object',
              properties: { data: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, amount: { type: 'integer' } } } } },
            }),
            '401': errResp,
          },
        },
        post: {
          operationId: 'createCharge',
          summary: 'Create a charge',
          tags: ['Charges'],
          requestBody: {
            required: true,
            content: {
              'application/x-www-form-urlencoded': {
                schema: {
                  type: 'object',
                  required: ['amount', 'currency'],
                  properties: { amount: { type: 'integer' }, currency: { type: 'string' }, source: { type: 'string' } },
                },
              },
            },
          },
          responses: { '200': jsonResp('Charge'), '402': errResp },
        },
      },
      '/v1/charges/{id}': {
        get: {
          operationId: 'getCharge',
          summary: 'Retrieve a charge',
          tags: ['Charges'],
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: { '200': jsonResp('Charge'), '404': errResp },
        },
      },
      '/v1/customers': {
        get: {
          operationId: 'listCustomers',
          summary: 'List customers',
          tags: ['Customers'],
          parameters: [{ name: 'limit', in: 'query', schema: { type: 'integer' } }],
          responses: { '200': jsonResp('Customers', { type: 'object', properties: { data: { type: 'array', items: customer } } }) },
        },
        post: {
          operationId: 'createCustomer',
          summary: 'Create a customer',
          tags: ['Customers'],
          requestBody: {
            content: {
              'application/x-www-form-urlencoded': {
                schema: { type: 'object', properties: { email: { type: 'string' }, name: { type: 'string' } } },
              },
            },
          },
          responses: { '200': jsonResp('Customer', customer), '400': errResp },
        },
      },
    },
  });
}

export function templateSpec(id: TemplateId): string {
  switch (id) {
    case 'gemini': return geminiSpec();
    case 'openai': return openaiSpec();
    case 'github': return githubSpec();
    case 'stripe': return stripeSpec();
    default: throw new Error(`No generated contract for template "${id}"`);
  }
}
